// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ai-proxy-ice/IceCloud.tsx": () => import("../components/mockups/ai-proxy-ice/IceCloud.tsx"),
  "./components/mockups/ai-proxy-ice-copy-1GH556P1/AiProxyIceCopy1GH556P1.tsx": () => import("../components/mockups/ai-proxy-ice-copy-1GH556P1/AiProxyIceCopy1GH556P1.tsx"),
  "./components/mockups/ai-proxy-hub/Dashboard.tsx": () => import("../components/mockups/ai-proxy-hub/Dashboard.tsx")
};
